name: DEVELOP-WORKFLOW

on:
  pull_request:
    types: [edited, opened, synchronize, closed]
  push:
    branches:
      - develop
  issue_comment:
    types: [created]

jobs:
    tag:
      name: Tag version
      if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.bump.outputs.version }}
      steps:
        - name: Checkout repository (full history)
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Compute next SemVer from commits
          id: bump
          run: |
            set -euo pipefail
  
            # Ostatni tag (albo 0.0.0 jeśli brak)
            LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            echo "Last tag: $LAST_TAG"
  
            # Commity od ostatniego taga do HEAD
            COMMITS=$(git log --pretty=format:%s ${LAST_TAG}..HEAD || true)
  
            # Domyślna podbitka
            BUMP="patch"
  
            # Reguły zgodne z Conventional Commits
            if echo "$COMMITS" | grep -E 'BREAKING CHANGE|!:' -q; then
              BUMP="major"
            elif echo "$COMMITS" | grep -E '^feat(\(.+\))?:' -q; then
              BUMP="minor"
            elif echo "$COMMITS" | grep -E '^fix(\(.+\))?:' -q; then
              BUMP="patch"
            else
              # jeśli brak dopasowania, dalej patch
              BUMP="patch"
            fi
  
            # Parsowanie SemVer
            CUR=${LAST_TAG#v}
            IFS='.' read -r MAJ MIN PAT <<< "$CUR"
  
            case "$BUMP" in
              major) MAJ=$((MAJ+1)); MIN=0; PAT=0 ;;
              minor) MIN=$((MIN+1)); PAT=0 ;;
              patch) PAT=$((PAT+1)) ;;
            esac
  
            NEW="v${MAJ}.${MIN}.${PAT}"
            echo "New tag: $NEW"
  
            # Wystaw jako output dla kolejnych jobów
            echo "version=${NEW#v}" >> "$GITHUB_OUTPUT"
            echo "new_tag=$NEW" >> "$GITHUB_OUTPUT"
  
        - name: Create & push git tag
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "${{ steps.bump.outputs.new_tag }}"
            git push origin "${{ steps.bump.outputs.new_tag }}"
